id: "simple-plugin-client"
name: "Simple Plugin Example"
description: "Простой пример плагина для Yapay SDK"
domain: "example.com"
enabled: true
security:
  request_enforcement: monitor  # strict | origin | monitor
  rate_limit: 100
  cors:
    origins:
      - "https://example.com"
      - "https://www.example.com"
      - "http://localhost:3000"
metadata:
  version: "1.0.0"
  author: "Metalmon"
  support_email: "dev@frappecrm.ru"
  website: "https://frappecrm.ru"
  business_type: "example"

yandex:
  merchant_id: "your-yandex-merchant-id"
  secret_key: "your-yandex-secret-key"
  sandbox_mode: true
  currency: "RUB"

notifications:
  telegram:
    enabled: false
    chat_id: "your-telegram-chat-id"
    bot_token: "your-telegram-bot-token"
  email:
    enabled: false
    smtp_host: ""
    smtp_port: 587
    username: ""
    password: ""
    from: ""

field_labels:
  product_id: "ID товара"
  user_id: "ID пользователя"
  product_name: "Название товара"
