services:
  # Main development container for YAPAY SDK
  yapay-sdk-development:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
      args:
        GOPROXY: "https://proxy.golang.org,direct"
        GOSUMDB: "sum.golang.org"
    volumes:
      - ..:/workspace/sdk:cached
      # Mount the Docker socket to allow running Docker commands from within the container (Docker-out-of-Docker)
      - /var/run/docker.sock:/var/run/docker.sock
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    environment:
      # Pass the host project path to the container, so it can be used for Docker-out-of-Docker volume mounts.
      - HOST_PROJECT_PATH=${PWD}
      - GO111MODULE=on
      - GOPROXY=https://proxy.golang.org,direct
      - GOSUMDB=sum.golang.org
      - CGO_ENABLED=1
      - LOG_LEVEL=debug
      - YANDEX_SANDBOX_MODE=true
      - METRICS_PORT=8080
      - TERM=xterm-256color
      - COLORTERM=truecolor
    ports:
      - "8080:8080"  # YAPAY SDK main application
      - "8081:8081"  # YAPAY SDK debug port
      - "2345:2345"  # Delve debugger port
    command: sleep infinity
    networks:
      - yapay-sdk-development-network

  # Yandex Pay API mock service for development
  yandex-pay-mock:
    image: wiremock/wiremock:latest
    ports:
      - "8083:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command: ["--global-response-templating", "--verbose"]
    networks:
      - yapay-sdk-development-network

volumes:
  go-mod-cache:
  go-build-cache:

networks:
  yapay-sdk-development-network:
    driver: bridge