# GitHub Action для автоматического развертывания плагинов
# 
# ИНСТРУКЦИЯ ПО ВКЛЮЧЕНИЮ:
# 1. Настройте Secrets в настройках репозитория
# 2. Создайте пользователя deployer на сервере
# 3. Для автоматического запуска раскомментируйте строки ниже
#
# Подробная инструкция: docs/development/workflow.md

# Ручной запуск (всегда доступен)
on:
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild all plugins'
        required: false
        default: false
        type: boolean

# Раскомментируйте эти строки для автоматического запуска при пуше:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Запускаем для ручного запуска или для пуша в main ветку
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Build all plugins
      run: |
        cd yapay-sdk
        # Принудительная пересборка для ручного запуска с force_rebuild=true или для автоматического запуска
        if [ "${{ github.event.inputs.force_rebuild }}" = "true" ] || [ "${{ github.event_name }}" = "push" ]; then
          echo "Force rebuilding all plugins..."
          make clean
        fi
        make build-plugins
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Определяем параметры в зависимости от типа запуска
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            FORCE_REBUILD="${{ github.event.inputs.force_rebuild || 'false' }}"
          else
            # Автоматический запуск (push)
            FORCE_REBUILD="true"
          fi
          
          echo "Starting deployment..."
          echo "Force rebuild: $FORCE_REBUILD"
          echo "Trigger: ${{ github.event_name }}"
          
          # Создаем резервную копию текущих плагинов
          sudo mkdir -p /tmp/yapay-backup-$(date +%Y%m%d-%H%M%S)
          sudo cp -r ${{ secrets.PLUGINS_PATH }}/* /tmp/yapay-backup-$(date +%Y%m%d-%H%M%S)/ 2>/dev/null || true
          
          # Копируем только плагины из текущего репозитория (hot-reload автоматически подхватит изменения)
          for plugin_dir in /tmp/plugins/*; do
            if [ -d "$$plugin_dir" ]; then
              plugin_name=$$(basename "$$plugin_dir")
              echo "Deploying plugin: $$plugin_name"
              sudo mkdir -p ${{ secrets.PLUGINS_PATH }}/$$plugin_name
              sudo cp -r $$plugin_dir/* ${{ secrets.PLUGINS_PATH }}/$$plugin_name/
            fi
          done
          
          # Устанавливаем правильные права
          sudo chown -R ${{ secrets.PLUGINS_USER }} ${{ secrets.PLUGINS_PATH }}
          sudo chmod -R 755 ${{ secrets.PLUGINS_PATH }}
          
          # Проверяем статус сервера (без перезапуска)
          sudo systemctl status yapay --no-pager
          
          echo "Deployment completed successfully! Plugins hot-reloaded."
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: plugins-${{ github.sha }}
        path: yapay-sdk/plugins/
        retention-days: 30
