name: Release SDK

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Check compatibility
        run: make check-compatibility

      - name: Build example plugins
        run: make build-plugins

      - name: Test plugins
        run: make test-plugins

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            ## Changes in this Release

            See [CHANGELOG.md](CHANGELOG.md) for details.

            ## Installation

            ```bash
            go get github.com/metalmon/yapay-sdk@${{ github.ref_name }}
            ```

            ## Quick Start

            ```bash
            git clone https://github.com/metalmon/yapay-sdk.git
            cd yapay-sdk
            make new-plugin-my-plugin
            make build-plugin-my-plugin
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
